language: python
python:
  - "3.6"
services:
  - postgresql
before_script:
  - psql -c 'create database xplrio;' -U andreynovichkov
  - python manage.py migrate
install:
  - pip install -r requirements.txt
script:
  - python manage.py test