# Generated by Django 2.2.7 on 2019-11-25 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_graph'),
        ('xplrmain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='coordinates',
            field=models.CharField(default=(0, 0), max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpost',
            name='description',
            field=models.CharField(default='No description', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpost',
            name='difficulty',
            field=models.CharField(default='Easy', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpost',
            name='time_to_go',
            field=models.CharField(default='Any Time', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpost',
            name='verified',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userpost',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
        migrations.CreateModel(
            name='UserVisitedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xplrmain.UserPost')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserSavedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xplrmain.UserPost')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserGoPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xplrmain.UserPost')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
        migrations.AddField(
            model_name='userpost',
            name='go',
            field=models.ManyToManyField(to='xplrmain.UserGoPost'),
        ),
        migrations.AddField(
            model_name='userpost',
            name='saved',
            field=models.ManyToManyField(to='xplrmain.UserSavedPost'),
        ),
        migrations.AddField(
            model_name='userpost',
            name='visited',
            field=models.ManyToManyField(to='xplrmain.UserVisitedPost'),
        ),
    ]
