# Generated by Django 2.2.7 on 2019-12-02 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xplrmain', '0002_auto_20191202_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
