# Generated by Django 2.2.7 on 2019-12-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplrmain', '0002_auto_20191204_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='username',
            field=models.CharField(default='default_username', max_length=100, null=True),
        ),
    ]
