# Generated by Django 2.2.7 on 2019-12-02 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xplrmain', '0003_auto_20191202_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpost',
            old_name='user_id',
            new_name='user',
        ),
    ]
