from django.db import models
from accounts import models as account_model

# Create your models here.
class UserPost(model.Model):
    post_id = models.FloatField()  # Randomly generated byte
    user_id = models.ForeignKey(account_model.User, on_delete=models.CASCADE)  # Many to One relationship
