# Generated by Django 2.2.7 on 2019-12-03 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', help_text='First name', max_length=32)),
                ('last_name', models.CharField(default='', help_text='Last name', max_length=32)),
                ('email', models.EmailField(default='', help_text='Enter a valid email address', max_length=64)),
                ('photography_type', models.CharField(default='', max_length=500, null=True)),
                ('risk_level', models.CharField(default='', max_length=500, null=True)),
                ('profile_pic', models.ImageField(default='', max_length=500, null=True, upload_to='')),
                ('recent_ip', models.GenericIPAddressField(default='27.0.0.0', null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
